#!/usr/bin/env python3
"""Regenerate `data/real_private/MANIFEST.toml`.

SPEC 0003 R3.3. The manifest is the only part of `data/real_private/` that is committed, and
it is what lets a reviewer see exactly which records a result rests on without receiving any
of them. It is generated rather than hand-written because there are sixty-odd files and a
hand-maintained list would drift on the first addition.

    python scripts/make_data_manifest.py

The sha256 recorded here is the same digest the run identity folds in, so the manifest is a
human-readable view of a hash the pipeline computes anyway.
"""

from __future__ import annotations

import hashlib
import re
from datetime import date
from pathlib import Path

PRIVATE_ROOT = Path(__file__).resolve().parent.parent / "data" / "real_private"
MANIFEST = PRIVATE_ROOT / "MANIFEST.toml"

# Everything under data/real_private/ is embargoed; the field exists so a future record that
# is not can say so without changing the schema.
DEFAULT_EMBARGO = "embargoed"

# `DDMMYY_<device>_qubit<N>[_suffix]` - the convention the run-start resolver also reads.
STEM = re.compile(r"^(\d{2})(\d{2})(\d{2})_(\w+?)_qubit(\d+)(?:_(\w+))?$")


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _provenance(path: Path) -> dict[str, str]:
    """What can be said about a file from its name and location, and nothing more.

    Deliberately does not open the pickle. A manifest that had to load every record would
    couple the inventory to the schema, and the point of the inventory is to work when the
    records are absent.
    """
    group = path.parent.name
    info: dict[str, str] = {"group": group}
    match = STEM.match(path.stem)
    if match:
        day, month, year, device, qubit, suffix = match.groups()
        info["device"] = device
        info["qubit"] = qubit
        info["run_date"] = f"20{year}-{month}-{day}"
        if suffix:
            info["condition"] = suffix
    elif path.stem.endswith("_freq_log"):
        info["device"] = path.stem.split("_")[0]
        info["kind"] = "calibration log"
        qubit = re.search(r"qubit(\d+)", path.stem)
        if qubit:
            info["qubit"] = qubit.group(1)
    return info


def _quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build() -> str:
    if not PRIVATE_ROOT.is_dir():
        raise SystemExit(f"no such directory: {PRIVATE_ROOT}")

    files = sorted(
        (p for p in PRIVATE_ROOT.rglob("*") if p.is_file() and p.name != MANIFEST.name),
        key=lambda p: str(p.relative_to(PRIVATE_ROOT)),
    )

    lines = [
        "# GENERATED by scripts/make_data_manifest.py. Do not hand-edit.",
        "#",
        "# An inventory of the private records, committed so that a result can be audited by",
        "# someone who will never receive them. The files themselves are gitignored.",
        "#",
        "# `sha256` is the digest the run identity folds in: if a record here differs from the",
        "# one a figure was computed from, the identities will not match either.",
        "",
        "[manifest]",
        f"generated = {_quote(date.today().isoformat())}",
        f"file_count = {len(files)}",
        f"total_bytes = {sum(p.stat().st_size for p in files)}",
        "",
    ]

    for path in files:
        rel = path.relative_to(PRIVATE_ROOT)
        lines.append("[[record]]")
        lines.append(f"path = {_quote(str(rel))}")
        lines.append(f"sha256 = {_quote(_sha256(path))}")
        lines.append(f"bytes = {path.stat().st_size}")
        lines.append(f"embargo = {_quote(DEFAULT_EMBARGO)}")
        for key, value in _provenance(path).items():
            lines.append(f"{key} = {_quote(value)}")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    MANIFEST.write_text(build())
    print(f"wrote {MANIFEST} ({MANIFEST.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
